/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        secondary: "#5a5f62",
        "surface-variant": "#e4e2e4",
        "on-primary-container": "#7c839b",
        outline: "#76777d",
        "on-secondary": "#ffffff",
        "secondary-container": "#dce0e4",
        "surface-container-high": "#eae7e9",
        "on-error": "#ffffff",
        "on-surface-variant": "#45464d",
        surface: "#fcf8fa",
        "inverse-on-surface": "#f3f0f2",
        "on-error-container": "#93000a",
        "on-secondary-container": "#5e6367",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e4e2e4",
        "surface-bright": "#fcf8fa",
        primary: "#000000",
        "inverse-primary": "#bec6e0",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1b1b1d",
        "surface-tint": "#565e74",
        background: "#fcf8fa",
        "on-background": "#1b1b1d",
        "surface-container-low": "#f6f3f5",
        "outline-variant": "#c6c6cd",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0edef",
        "surface-dim": "#dcd9db",
        "primary-container": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "1rem",
        "container-max": "1280px",
        lg: "2.5rem",
        gutter: "24px",
        md: "1.5rem",
        xs: "0.5rem",
        base: "4px",
        xl: "4rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontSize: {
        "headline-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "700" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "700" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "700" }],
        "body-md": ["1rem", { lineHeight: "1.5rem" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem" }],
        "label-caps": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.08em" }],
      },
    },
  },
  plugins: [],
};